### ISSUE TITLE
Plugin 7.10.0 "No kibana plugins found in archive"

### ISSUE THREAD

**Issue by amorrowbellarmine** [nsano-rururu/elastalert-kibana-plugin#107]
I would first like to greatly express my appreciation to you for maintaining the Elastalert Server and Kibana plugin. I've been working to get them setup in my environment this month after learning about them during an infosec conference.

I had the plugin setup and working on Kibana 7.9.3 in my test environment. When I upgraded to 7.10.0 and ran into issues. During installation of the plugin for 7.10.0 I get `"No kibana plugins found in archive"` error. I tried a fresh Ubuntu server and got the same error

Command and output:
```
sudo /usr/share/kibana/bin/kibana-plugin install https://github.com/nsano-rururu/elastalert-kibana-plugin/releases/download/1.3.0/elastalert-kibana-plugin-1.3.0-7.10.0.zip --allow-root
Found previous install attempt. Deleting...
Attempting to transfer from https://github.com/nsano-rururu/elastalert-kibana-plugin/releases/download/1.3.0/elastalert-kibana-plugin-1.3.0-7.10.0.zip
Transferring 22305746 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"
```

Server info:
Ubuntu 20.04
Kibana & Elasticsearch 7.10.0 (not running in docker)

**Comment by nsano-rururu** [comment]
As I wrote below, support for the old format kibana-plugin has been removed in kibana 7.10.0. That will result in an error. It is impossible to run it without rewriting the program with the new format of writing kibana-plugin. I have no knowledge of kibana-plugin, so it may not be possible for me anymore.
https://github.com/nsano-rururu/elastalert-kibana-plugin/issues/69#issuecomment-690772982

**Comment by nsano-rururu** [comment]
The current situation is that it is difficult to spend too much time on development because most of the time is spent responding to issues.

**Answer to issue**

https://github.com/Yelp/elastalert
https://github.com/bitsensor/elastalert
https://github.com/bitsensor/elastalert-kibana-plugin
https://github.com/johnsusek/praeco

**Since August of this year, I have been the maintainer of the following Praeco and Elast Alert Servers.**

https://github.com/johnsusek/elastalert-server
https://github.com/johnsusek/praeco

**I'm submitting a pull request to ElastAlert about a bug found when adding features to Praeco and ElastAlert Server.**

- Fix logging.warn to logging.warning 
- added docs hive_verify 
- added docs alerta_api_skip_ssl 
- Fix docs VictorOps to Splunk On-Call 
- Fix docs external link URL 
- Remove the forgotten code of new_style_string_format 
- Fix Stomp 
- Fix docs stomp 
- Change Library blist to sortedcontainers 
- Update README Third Party Tools And Extras Info 
- Pin tzlocal to 2.1 in setup.py 
- Remove configparser 
- Remove cffi 
- added docs slack_ignore_ssl_errors 
- [WIP] Python3.8 support 
- added docs slack_ca_certs 
- Fix PyYAML Deprecated Warning 
- Update docs Running ElastAlert 
- added docs telegram_proxy_login and telegram_proxy_pass 
- added docs pagertree_proxy 
- Fix PagerTree 
- Kibana Discover app link 7.4/7.5/7.6/7.7/7.8/7.9 support 
- Remove Stride integration 
- Sync requirements.txt and setup.py & update py-zabbix 
- added docs opsgenie_proxy 
- Fix docs opsgenie 
- Fix Zabbix(Docs & schema.yaml) 
- Fix SNS(Program & Docs) 
- Fix LineNotify

**Comment by nsano-rururu** [comment]
Please think that there is no support for the new Kibana for the time being

**Comment by nsano-rururu** [comment]
If you are in a hurry, you can only say that you should do it yourself. I don't usually use Elast Alert so I don't have any problems so I have no reason to hurry up.

**Comment by nsano-rururu** [comment]
About OSS

Manuals may not be organized
The developer is not responsible for fixing the bug
In many cases, the support of the developer cannot be received

**Comment by nsano-rururu** [comment]
Needs refactoring the entire code

**Comment by nsano-rururu** [comment]
Please take a moment to learn how to make kibana-plugin

**Comment by nsano-rururu** [comment]
There are no plans to support it at this time.

**Comment by nsano-rururu** [comment]
The atmosphere is likely to take over the maintainers of Elast Alert, so check the situation and decide what to do.

**Comment by nsano-rururu** [comment]
@amorrowbellarmine 

We are starting to work with kibana 7.10 on the following branches. If you can handle it, merge it into the master branch and release it.
https://github.com/nsano-rururu/elastalert-kibana-plugin/tree/migrating-plugin-new-platform

**Comment by nsano-rururu** [comment]
@amorrowbellarmine

I haven't confirmed if it works properly, but it seems that there is a release that supports kibana 7.10. Why don't you give it a try?
https://github.com/ch-bas/elastalert-kibana-plugin

**Comment by balusarakesh** [comment]
@nsano-rururu 
I tried that repo with the following Dockerfile and it doesn't seem to work
```
FROM docker.elastic.co/kibana/kibana:7.10.0
RUN /usr/share/kibana/bin/kibana-plugin install https://github.com/ch-bas/elastalert-kibana-plugin/releases/download/1.3.1/elastalert-kibana-plugin-7.10.0.zip --allow-root
```

Here's the error I see
```
Attempting to transfer from https://github.com/ch-bas/elastalert-kibana-plugin/releases/download/1.3.1/elastalert-kibana-plugin-7.10.0.zip
Transferring 90230 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "Invalid plugin name [elastalert-kibana-plugin] in kibana.json, expected it to be valid camelCase"
The command '/bin/sh -c /usr/share/kibana/bin/kibana-plugin install https://github.com/ch-bas/elastalert-kibana-plugin/releases/download/1.3.1/elastalert-kibana-plugin-7.10.0.zip --allow-root' returned a non-zero code: 70
```

**Comment by nsano-rururu** [comment]
@balusarakesh

Thank you for sharing the information. It is highly possible that the operation has not been confirmed because the host name is specified in the environment variable instead of kibana.yml and the path of the URL of elastalert-server is modified for some reason.
>const uri = process.env.PROTOCOL + '://' + process.env.HOSTNAME + process.env.PORT;
https://github.com/ch-bas/elastalert-kibana-plugin/commit/ed6ce95b186811d1568a000dc202b1ce89d94722

https://github.com/ch-bas/elastalert-kibana-plugin/commit/b05c27a885327e38e3c994120f710c272c007877
https://github.com/ch-bas/elastalert-kibana-plugin/commit/ed6ce95b186811d1568a000dc202b1ce89d94722

**Comment by ch-bas** [comment]
@balusarakesh, thanks for sharing the information, I've built a new release that fixed that problem.

**Comment by Karql** [comment]
#143

**Comment by nsano-rururu** [comment]
Since we decided to use discussions, we will close existing issues.
https://github.com/nsano-rururu/elastalert-kibana-plugin/discussions
